In [12]:
import numpy as np
def vandermonde(input_arr):
    val = len(input_arr)
    out_arr = np.column_stack([input_arr**(val-1-i) for i in range(val)])
    return out_arr

arr = vandermonde(np.array([1,2,3,4]))
print(arr)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
